### ISSUE TITLE
Add to YARN

### ISSUE THREAD

**Issue by ghost** [sweetalert/sweetalert-with-react#2]
Hello there. First of all I want to say thank you. Second is could you please add this to npm packages?

**Comment by J-F-Liu** [comment]
```
> npm install  @sweetalert/react -S
npm ERR! Darwin 17.3.0
npm ERR! argv "/usr/local/Cellar/node/9.3.0/bin/node" "/usr/local/bin/npm" "install" "@sweetalert/react" "-S"
npm ERR! node v9.3.0
npm ERR! npm  v3.10.3
npm ERR! code E404

npm ERR! 404 Not found : @sweetalert/react
npm ERR! 404
npm ERR! 404  '@sweetalert/react' is not in the npm registry.
```

**Comment by iKonrad** [comment]
Any progress on getting this back on NPM?

**Comment by J-F-Liu** [comment]
I find that there is already an example of using `react` to render React element as dialog content:
https://sweetalert.js.org/guides/#using-dom-nodes-as-content

**Comment by t4t5** [comment]
It's finally released now :) https://www.npmjs.com/package/@sweetalert/with-react
