### ISSUE TITLE
Failed to build for production

### ISSUE THREAD

**Issue by dmaehler** [sweetalert/sweetalert-with-react#4]
Running `npm run build` is failing with the following message:

`Failed to minify the code from this file: 
 	./node_modules/@sweetalert/with-react/dist/sweetalert.js:14 `

Are there any specific settings needed in my react application to build this properly?

**Comment by t4t5** [comment]
I think you might need to add `sweetalert` as a project dependency too if you haven't already

**Comment by ghost** [comment]
me too but i checked in dependency but have **sweetalert**

**Comment by dmaehler** [comment]
I had  react-scripts in version 1.1.5, upgrading to 2.1.2 solved the problem.
